"""initial_schema

Revision ID: 873530ec7cbe
Revises: 
Create Date: 2026-06-22 16:40:15.353322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '873530ec7cbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tradovate_env', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secrets_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('point_value', sa.Float(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('profit_target', sa.Float(), nullable=False),
    sa.Column('consistency_pct', sa.Float(), nullable=False),
    sa.Column('max_contracts', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('risk_state',
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_eod_balance', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('signal',
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_uid'), ['uid'], unique=False)

    op.create_table('trade',
    sa.Column('uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signal_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.Enum('TP', 'SL', 'MANUAL', name='exitreason'), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='tradestatus'), nullable=False),
    sa.CheckConstraint('entry_price > 0', name='ck_trade_entry_price_gt_0'),
    sa.CheckConstraint('qty > 0', name='ck_trade_qty_gt_0'),
    sa.ForeignKeyConstraint(['signal_uid'], ['signal.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_uid'), ['uid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_uid'))
        batch_op.drop_index(batch_op.f('ix_trade_account_id'))

    op.drop_table('trade')
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_uid'))

    op.drop_table('signal')
    op.drop_table('risk_state')
    op.drop_table('account')
    # ### end Alembic commands ###
